(function() {var implementors = {};
implementors["byteorder"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='byteorder/enum.BigEndian.html' title='byteorder::BigEndian'>BigEndian</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='byteorder/enum.LittleEndian.html' title='byteorder::LittleEndian'>LittleEndian</a>",];
implementors["parity_wasm"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarUint32.html' title='parity_wasm::elements::VarUint32'>VarUint32</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarUint64.html' title='parity_wasm::elements::VarUint64'>VarUint64</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarUint7.html' title='parity_wasm::elements::VarUint7'>VarUint7</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarInt7.html' title='parity_wasm::elements::VarInt7'>VarInt7</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarInt32.html' title='parity_wasm::elements::VarInt32'>VarInt32</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarInt64.html' title='parity_wasm::elements::VarInt64'>VarInt64</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.Uint32.html' title='parity_wasm::elements::Uint32'>Uint32</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.Uint64.html' title='parity_wasm::elements::Uint64'>Uint64</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='parity_wasm/elements/struct.VarUint1.html' title='parity_wasm::elements::VarUint1'>VarUint1</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='parity_wasm/elements/enum.ValueType.html' title='parity_wasm::elements::ValueType'>ValueType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='parity_wasm/elements/enum.BlockType.html' title='parity_wasm::elements::BlockType'>BlockType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
